### ISSUE TITLE
Library hidden in Tautulli show up in current activity on discord

### ISSUE THREAD

**Issue by k2gremlin** [nwithan8/tauticord#102]
Would there be anyway to filter out specific libraries and not post messages about content being played from that library? 
Using docker with environment variables.

**Comment by nwithan8** [comment]
I've never hidden a library in Tautulli (didn't know you can do that), and it's odd that Tautulli would return a stream in that library if it is marked hidden.

I'll have to see if Tautulli's API indicates if a library is hidden or not.

**Comment by k2gremlin** [comment]
So in Taut, you have the option to ‘delete’ a library so it doesn’t retain statistics for that library. But something played from that Library still shows up in now playing. May make it hard if not impossible to filter out.

**Comment by nwithan8** [comment]
I can't find anywhere in Tautulli's API documentation that it returns the "hidden" status of a library. I'd recommend opening an issue on Tautulli asking for that to be exposed in their API.
