### ISSUE TITLE
Tautulli self-signed certificate error

### ISSUE THREAD

**Issue by ChadOhman** [nwithan8/tauticord#103]
Hi there,

I run Tautulli through Swizzin and it receives a self-signed certificate. I'm receiving this error when I boot the Docker image:
`[CRITICAL]: Fatal error occurred. Shutting down: Could not begin a Tautulli connection. Please check that your configuration is complete and reachable. Exception: HTTPSConnectionPool(host='10.0.0.40', port=443): Max retries exceeded with url: /tautulli/api/v2?apikey=REDACTED&cmd=get_tautulli_info (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))`

Is there an environment variable I can add to allow it to ignore the SSL cert validation error?

Thanks in advance.

**Comment by nwithan8** [comment]
Not right now, this is something I would need to add support for upstream, in the Tautulli API library that Tauticord uses.
