### ISSUE TITLE
Assigning channelIDs manually

### ISSUE THREAD

**Issue by MS0x0539** [nwithan8/tauticord#104]
Not an issue but a feature request

I've noticed that my Tauticord sometimes generates new channels even though the channels existed before. This seems to happen the most with 'Current streams', 'Current transcodes', 'Bandwith' for me. I've also had it duplicate the library channels once or twice but not as often as the others.

Manually assigning channels with their dedicated channelID would prevent this from happening, while it does require more work for people starting to use Tauticord, it does save a lot of troubleshoot / deleting channels.

**Comment by poweruser15** [comment]
Yes please! We need this. Would be awesome for us to manually create and decide how the channels be organized and assigned
