### ISSUE TITLE
New Feature: Disk space usage.

### ISSUE THREAD

**Issue by tecnobrat** [nwithan8/tauticord#113]
Disk space is probably one of the most interesting performance metrics for a large library.

I would love to see along side CPU and memory usage, disk usage. Would need to be able to specify a disk to monitor (EG: my config for tauticord is on a separate disk from my library). For docker-based setups we could simply mount `/media` and tauticord always watches that for usage. For non-docker they would need to specify a disk/mount point instead.

I'm updating it manually for now, but mine looks like this:
![image](https://github.com/nwithan8/tauticord/assets/145406/c249a904-5636-46b2-a5e0-52fc1c0afde8)

**Comment by coolfreak55** [comment]
Adding in another support for this request.. would be really nice

**Comment by nwithan8** [comment]
Which is better for when the space used and the total space available are in different units?

```
Use different units - 5 MB / 100 TB (1.25%)
Use the units of the smaller number - 5 / 100000000 MB (1.25%)
Use the units of the larger number - 0.00000005 / 100 TB (1.25%)
```

**Comment by coolfreak55** [comment]
Awesome work! I also agree the first one is preferred. In an ideal world, this should be a rather rare occurrence as I would think most configurations will have multiple TB used and free.
