### ISSUE TITLE
Status channel keeps re-creating when container reboots

### ISSUE THREAD

**Issue by k2gremlin** [nwithan8/tauticord#119]
I'll try to capture the logs the next time the container stops for whatever reason. However, when restarting the container everything  starts working properly again. 

However, even just making updates to channel names etc. and redeploying the container, the 
"TC_DISCORD_CHANNEL_NAME=Tautulli-Status" keeps making a new text channel instead of resuming in the channel that already exists. 

Can try to provide logs if needed. 

Screenshot Link - https://prnt.sc/twf0yutNTq27

**Comment by nwithan8** [comment]
Your configured channel name needs to be all lowercase to match Discord's naming conventions.

**Comment by k2gremlin** [comment]
Wow, thanks for the super fast response. Let me know if there is anything I can do to assist with development. Love the bot :)
