### ISSUE TITLE
Timezone Help

### ISSUE THREAD

**Issue by iTzEthqnHD** [nwithan8/tauticord#13]
Hi, I am in the Eastern time zone, I put EST in and works, but is an hour off. So I tried EDT and ET but the gave me an error saying that was invalid. How do I adjust for daylight savings time and such?

**Comment by iTzEthqnHD** [comment]
And how can I make the bot say "Ready!" in the console when it has booted up?

**Comment by iTzEthqnHD** [comment]
One more thing. When 1 specific user is streaming, the embed doesn't list the stream, but it has an emoji so I can stop the stream. This error is in the console: "ERROR:Precision not allowed in integer format specifier"

Am I doing something wrong?

**Comment by ItsM3rry** [comment]
Same probleme, I'm not in UTC but in CEST and the bot print the same message @nwithan8
