### ISSUE TITLE
Customize "PlexStatus" channel name

### ISSUE THREAD

**Issue by Metuant** [nwithan8/tauticord#130]
Possible to allow customization of the channel name for "PlexStatus" option?

**Comment by nwithan8** [comment]
I'm curious, what would you rename it to?

You can remap the channel to a different channel ID if you want.

**Comment by Metuant** [comment]
Would prefer "Friendly server name: Online/Offline"

First inclination was map to a channel ID as recommended but tauticord renames to the "Plex Server: Online/Offline"

Does this clarify?

**Comment by nwithan8** [comment]
Yes, that clarifies it.

Unfortunately, renaming the channel would introduce a breaking change for those currently using Tauticord that I don't believe is justified with the change.

You can always rename the voice channel category that the "Plex Status" channel is in, if you are attempting to do some sort of multi-server setup and need to specify which Plex server is being monitored.
