### ISSUE TITLE
No actualization

### ISSUE THREAD

**Issue by ItsM3rry** [nwithan8/tauticord#15]
Hello,

The bot doesn't seem to actualize Discord Voice Channels or Embed message

**Comment by ItsM3rry** [comment]
Since I started the bot on Sept 11, none of the libraries stats, or currents streamings (10 chans in total) has been updated.
Tried to restart the bot multiple times with no result

**Comment by ItsM3rry** [comment]
An if possible can you add mode info about Docker, like a compose file please

**Comment by nwithan8** [comment]
Can you provide logs? Is there an error it's reporting?

**Comment by ItsM3rry** [comment]
Sorry for the wait, here’s my latest logs:

https://pastebin.com/0ynYaWqy

- No voice channels created
- Init message not updated

**Comment by nwithan8** [comment]
Log link has expired. Is this still an issue?

**Comment by nwithan8** [comment]
Closing due to no response. Cannot reproduce.
