### ISSUE TITLE
New library added to config.yaml won't create additional voice channels, do I need to do anything else?

### ISSUE THREAD

**Issue by aaronduce** [nwithan8/tauticord#150]
<img width="727" alt="Screenshot 2024-01-29 at 14 59 27" src="https://github.com/nwithan8/tauticord/assets/20649108/c05120ce-94d7-46ac-8f94-4451931bba6a">

added Anime Movies, but nothing I do will make it create the additional voice channel(s)?

Am I missing something?

<img width="320" alt="Screenshot 2024-01-29 at 14 59 51" src="https://github.com/nwithan8/tauticord/assets/20649108/f55feabd-6cfa-435e-80a6-f3d433b9c758">

**Comment by nwithan8** [comment]
Have you restarted the bot since updating your config? What version are you running? Do you have any logs you can share? Does the library "Anime Movies" exist in Plex/Tautulli?

**Comment by aaronduce** [comment]
As it turns out, and no idea how, Enable had somehow gone to false under libraries section of config.
