### ISSUE TITLE
Looking for way to send update to discord when new content is added

### ISSUE THREAD

**Issue by benedlore** [nwithan8/tauticord#155]
Is that possible with Tauticord out of the box? Was trying to avoid writing my own bot if I can do that here. Not interested in the analytics or stream info, would probably disable all of that, just wanted to send a little message if a new item was added to Plex.

**Comment by nwithan8** [comment]
I'd recommend looking at the Webhooks and Notification Agents built into Tautulli: https://github.com/Tautulli/Tautulli/wiki/Notification-Agents-Guide#discord
