### ISSUE TITLE
Library Stats Aggregate

### ISSUE THREAD

**Issue by upamanyudas** [nwithan8/tauticord#157]
I have multiple libraries for movies and tv broken down by certain common factors (eg Animation, Documentary etc). I would like to show the aggregate numbers when showing the stats on the server. Would be great if it could be achieved.
Are there any workarounds currently? Or would it have to be an enhancement?

**Comment by nwithan8** [comment]
By aggregate, you mean instead of seeing "Movies - Animation", "Movies - Documentaries", etc. in the voice channels, you just want "Movies" with the total from all the different movie libraries?

**Comment by upamanyudas** [comment]
Yes exactly that.
