### ISSUE TITLE
Bandwidth displayed at wrong speed.

### ISSUE THREAD

**Issue by mtrogman** [nwithan8/Tauticord#17]
https://github.com/nwithan8/Tauticord/blob/329309cfc79fb3664d2d3d18f18b1f487cf5b216/modules/utils.py#L21-L24

Example: a 10.6 Mbps stream will read as 10.6 Kbps with math above.  

Should be:
    KB = float(1)
    MB = float(1024)  
    GB = float(MB ** 2)  
    TB = float(MB ** 3)

**Comment by nwithan8** [comment]
Fixed in 3fd6c9290454de9a8347ded1fc416bb32f701210
