### ISSUE TITLE
Plex Status Emoji not displaying

### ISSUE THREAD

**Issue by corruptmods** [nwithan8/tauticord#174]
Upon enabling plex status with emoji the online status is "Plex Status:" and no emoji is displayed. The bot has the required permissions to upload.

With Emoji set to True
![With](https://github.com/nwithan8/tauticord/assets/13516012/695ff2f6-21e2-48a3-836e-2456a5384d07)

Without Emoji set to True
![Without](https://github.com/nwithan8/tauticord/assets/13516012/643fd097-ac49-4601-b53b-f565fe4decc5)

**Comment by nwithan8** [comment]
@corruptmods Can you provide logs?

**Comment by corruptmods** [comment]
Attached are logs with emoji set to true and not displaying. 

[tauticord.csv](https://github.com/nwithan8/tauticord/files/14641855/tauticord.csv)

**Comment by corruptmods** [comment]
Attached are the logs.

[Tauticord.log](https://github.com/nwithan8/tauticord/files/14641902/Tauticord.log)

**Comment by nwithan8** [comment]
Thanks @corruptmods , this has been fixed in [v4.1.3](https://github.com/nwithan8/tauticord/releases/tag/4.1.3)
