### ISSUE TITLE
only send mesage on state change

### ISSUE THREAD

**Issue by TomW1605** [nwithan8/Tauticord#2]
this is a great bot however i think it would be better if it only sent a mesage when the state actualy changes.

i think a good way to do this would be to store the state and compair it to the new state pulled from Tautulli befor actualy sending a message

**Comment by twilsonco** [comment]
Have you also implemented this change? If so, double please fork!

**Comment by TomW1605** [comment]
im going to close this issue now as it is done all bar a PR. any mor issues/requests open a new issue in https://github.com/TomW1605/Tauticord/issues
