### ISSUE TITLE
[HELP] - 2 libraries with the same name, how to select the new one ? 

### ISSUE THREAD

**Issue by NeZios** [nwithan8/tauticord#206]
### This issue has not already been resolved

- [X] I have verified that no one has asked for help with this issue before.

### You have read the documentation

- [X] I have read the documentation and my issue is not addressed there.

### Installation Type

Docker on Unraid

### Configuration Type

Configuration File

### Type of Issue

Configuration (e.g settings not being applied)

### Issue Details

Hi, 
I had a problem with my library Movies so I had to delete it and create a new one. 
I now have 2 libraries with the same name in Tautulli including one obsolete. I do not want to delete it to keep track on history. 
When I give tauticord my library name in the yaml file, Tauticord selects the wrong library. 
![image](https://github.com/nwithan8/tauticord/assets/38002539/531795a2-ad47-4e7f-8163-797ea5cdc9c7)

Here is the log : 
<img width="1366" alt="image" src="https://github.com/nwithan8/tauticord/assets/38002539/93399147-5d80-46b0-867f-ace572162d8b">

So Tauticord selects the library "Films" with the section_id=8, whereas I need the new library "Films" with the section_id=10.

Thanks in advance for your help! 

### Steps to Reproduce

Requirements : having 2 libraries with the same name in Tautulli. In the YAML file, enter the name of the library. 

### Logs

```
07/04/2024
11:49:15
2024-04-07 11:49:15,183 - [INFO]: Updating library stats...
07/04/2024
11:49:15
INFO:Updating library stats...
07/04/2024
11:49:15
2024-04-07 11:49:15,184 - [INFO]: Collecting stats about library "Films"
07/04/2024
11:49:15
INFO:Collecting stats about library "Films"
07/04/2024
11:49:15
DEBUG:JSON returned by GET request: {'row_id': 1, 'server_id': 'XXXXXXXXXXXXXXXXXXXXXX', 'section_id': 8, 'section_name': 'Films', 'section_type': 'movie', 'library_thumb': '/:/resources/video.png', 'library_art': '/:/resources/movie-fanart.jpg', 'count': 5237, 'parent_count': None, 'child_count': None, 'is_active': 0, 'do_notify': 1, 'do_notify_created': 1, 'keep_history': 1, 'deleted_section': 0, 'last_accessed': None}
07/04/2024
11:49:15
2024-04-07 11:49:15,213 - [INFO]: Retrieving latest version information from GitHub
07/04/2024
11:49:15
INFO:Retrieving latest version information from GitHub
07/04/2024
11:49:15
2024-04-07 11:49:15,614 - [INFO]: Updated 🎬 Films: 5237 successfully
07/04/2024
11:49:15
INFO:Updated 🎬 Films: 5237 successfully
```

**Comment by cyb3rgh05t** [comment]
combine those "Films" libraries :)

https://github.com/cyb3rgh05t/tauticord/blob/dev/documentation/DOCUMENTATION.md#combined-libraries

**Comment by NeZios** [comment]
> combine those "Films" libraries :)
> 
> https://github.com/cyb3rgh05t/tauticord/blob/dev/documentation/DOCUMENTATION.md#combined-libraries

Does not work, it add the 2 "Films" libraries with the same ID. 
Here is the logs : 

<img width="1393" alt="image" src="https://github.com/nwithan8/tauticord/assets/38002539/c06d9362-ac4c-4b77-8f06-42bbefdd3f12">

Here is my YAML configuration : 

<img width="530" alt="image" src="https://github.com/nwithan8/tauticord/assets/38002539/dbb6a48a-6c99-411a-8e8e-e630f9bdca19">

Thanks for the help!

**Comment by nwithan8** [comment]
This is going to require a feature change, working on it.
