### ISSUE TITLE
[HELP] How do I turn off the "terminate stream" function?

### ISSUE THREAD

**Issue by engels74** [nwithan8/tauticord#216]
### This issue has not already been resolved

- [X] I have verified that no one has asked for help with this issue before.

### You have read the documentation

- [X] I have read the documentation and my issue is not addressed there.

### Installation Type

Docker Compose

### Configuration Type

Configuration File

### Type of Issue

Configuration (e.g settings not being applied)

### Issue Details

Previously you could set `PlexPass` to `false` and disable the Terminate Stream function.

Now it doesn't seem to do anything. I really want to be able to disable that feature, as I don't use it, and it's a bit much for my taste.

### Steps to Reproduce

1) Have PlexPass
2) Use Tauticord
3) Terminate Stream is enabled by default, [1] [2] [3] appearing under Streams.

### Logs

https://logs.notifiarr.com/?704fdf6e61a5a0b3=#FibGaA1qP6G8Uzs4QeyHtYuVFNY6r7WJwwX59EcEDZhp

**Comment by nwithan8** [comment]
This feature has been implemented in v5.4.0
