### ISSUE TITLE
[HELP] - Tauticord - Incorrect API key (but is correct)

### ISSUE THREAD

**Issue by Psychowebber** [nwithan8/tauticord#219]
### This issue has not already been resolved

- [X] I have verified that no one has asked for help with this issue before.

### You have read the documentation

- [X] I have read the documentation and my issue is not addressed there.

### Installation Type

Standalone Docker

### Configuration Type

Configuration File

### Type of Issue

Running (e.g. Tauticord not starting)

### Issue Details

I recently updated Tautulli to the latest version, now Tauticord is throwing an error and won't start.

### Steps to Reproduce

Update Tautulli to latest version
Try to start tauticord

### Logs

___________________  ______________________________________________ 
___  __/__    |_  / / /__  __/___  _/_  ____/_  __ \__  __ \__  __ \
__  /  __  /| |  / / /__  /   __  / _  /    _  / / /_  /_/ /_  / / /
_  /   _  ___ / /_/ / _  /   __/ /  / /___  / /_/ /_  _, _/_  /_/ / 
/_/    /_/  |_\____/  /_/    /___/  \____/  \____/ /_/ |_| /_____/  
Version 5.4.1, Python 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014]
Copyright © 2024 Nate Harris. All rights reserved.
2024-06-08 02:23:12,075 - [INFO]: Migration 001 skipped
2024-06-08 02:23:12,075 - [INFO]: Migration 002 skipped
2024-06-08 02:23:12,095 - [INFO]: Connecting to Tautulli at http://REDACTED:8181...
2024-06-08 02:23:12,106 - [CRITICAL]: Fatal error occurred. Shutting down: Could not begin a Tautulli connection. Please check that your configuration is complete and reachable. Exception: Invalid apikey (status code: 400)
CRITICAL:Fatal error occurred. Shutting down: Could not begin a Tautulli connection. Please check that your configuration is complete and reachable. Exception: Invalid apikey (status code: 400)
2024-06-08 02:23:12,106 - [CRITICAL]: Exiting with code 1
CRITICAL:Exiting with code 1
2024-06-08T02:23:12: PM2 log: App [tauticord:1] exited with code [1] via signal [SIGINT]
2024-06-08T02:23:12: PM2 log: App [tauticord:1] starting in -fork mode-
2024-06-08T02:23:12: PM2 log: App [tauticord:1] online

**Comment by vember31** [comment]
Assuming the 'latest' version of Tautulli you've installed is 2.14.x, it is not yet supported by Tauticord.  Tautulli v2.14.x will require Tauticord to adjust around Tautulli's new API requirements, so only versions 2.13.x and 2.12.x are supported by Tauticord today.

This is called out in the [documentation](https://github.com/nwithan8/tauticord/blob/master/documentation/DOCUMENTATION.md).  Downgrading your Tautulli version to 2.13.x will fix your issue.

**Comment by Psychowebber** [comment]
I managed to triage it. When I was updating the service, adjusting the environment details (portainer) for the API key and Bot token didn't work. I had to manually log edit the files and the bot worked properly. Unsure why it wasn't updating by pushing the environment flags, but this resolved the issue.

**Comment by nwithan8** [comment]
> Assuming the 'latest' version of Tautulli you've installed is 2.14.x, it is not yet supported by Tauticord. Tautulli v2.14.x will require Tauticord to adjust around Tautulli's new API requirements, so only versions 2.13.x and 2.12.x are supported by Tauticord today.
> 
> This is called out in the [documentation](https://github.com/nwithan8/tauticord/blob/master/documentation/DOCUMENTATION.md). Downgrading your Tautulli version to 2.13.x will fix your issue.

As is says in the log file you posted, it skipped migration 001 and 002, which migrate environmental variables to the config files and update the config file schema, respectively. Because you already had the required `tauticord.yaml` config file present, it didn't run the migration, meaning any changes to your environmental variables weren't getting picked up. Tauticord no longer uses environmental variables and, other than the initial migration as needed, their values will not be used. Any configuration changes now need to be made in the `tauticord.yaml` config file.

**Comment by nwithan8** [comment]
> Assuming the 'latest' version of Tautulli you've installed is 2.14.x, it is not yet supported by Tauticord. Tautulli v2.14.x will require Tauticord to adjust around Tautulli's new API requirements, so only versions 2.13.x and 2.12.x are supported by Tauticord today.
> 
> This is called out in the [documentation](https://github.com/nwithan8/tauticord/blob/master/documentation/DOCUMENTATION.md). Downgrading your Tautulli version to 2.13.x will fix your issue.

Thanks for reminding me. Tautulli v2.14 has been out of beta for a few weeks now, so Tauticord is going to officially add v2.14 support (and drop v2.12 and v2.13 support): https://github.com/nwithan8/tauticord/releases/tag/5.5.0
