### ISSUE TITLE
Bot won't start: tautaulli.api not found

### ISSUE THREAD

**Issue by TheMonDon** [nwithan8/tauticord#22]
`@WebServer:~/discord/tauticord$ python3 Tauticord.py
Traceback (most recent call last):
  File "/home/john/discord/tauticord/Tauticord.py", line 8, in <module>
    import modules.tautulli_connector as tautulli
  File "/home/john/discord/tauticord/modules/tautulli_connector.py", line 2, in <module>
    from tautulli.api import RawAPI
ModuleNotFoundError: No module named 'tautulli.api'`

Everything in config seems to be correct.

**Comment by TheMonDon** [comment]
I just tried installing it with docker that didn't work either

**Comment by nwithan8** [comment]
Did you install the dependencies already with `pip install -r requirements.txt`?

**Comment by TheMonDon** [comment]
> Did you install the dependencies already with `pip install -r requirements.txt`?

Yes I did

**Comment by NeZios** [comment]
Same problem here while trying to update Tauticord to try if it fix #16

**Comment by nwithan8** [comment]
Fixed in latest release
