### ISSUE TITLE
[BUG] - CPU and Memory reporting not consistently

### ISSUE THREAD

**Issue by identd113** [nwithan8/tauticord#227]
### This bug has not been reported already

- [X] I have verified that this bug has not already been reported.

### You have tried to fix the bug yourself

- [ ] I have tried to fix the bug myself.

### Current Behavior

When updating CPU and Memory reports and, while having the API exposed via the new Plex API reporting, we receive an error when reading the Plex API.  This does not occur right after restarting tauticord.

### Expected Behavior

The reports that use the Plex API, cpu and memory, would be updated during a refresh,  If the Plex Api is not able to be reached, keeping the value at the last known value would be preferable.  Indication in the channel name that this value has not been updated in a while would be great as well.

### Steps to Reproduce

Link environment to discord, and wait a period of time, and see the settings eventually report N/A

### Supporting Information

`2024-08-19 22:45:09,911 - [INFO]: Updating performance stats...
INFO:Updating performance stats...
DEBUG:Updating Users voice channel with new user count: 23
DEBUG:Updated 👤 User Count: 23 successfully
DEBUG:Updating Disk voice channel with new disk space: 1.1 TB/3.8 TB (27.92%)
DEBUG:Updated 💾 Disk: 1.1 TB/3.8 TB (27.92%) successfully
2024-08-19 22:45:10,408 - [ERROR]: No Plex API found to monitor CPU usage.
ERROR:No Plex API found to monitor CPU usage.
DEBUG:Updating CPU voice channel with new CPU percent: N/A
DEBUG:Updated 🧠 CPU: N/A successfully
2024-08-19 22:45:10,549 - [ERROR]: No Plex API found to monitor RAM usage.
ERROR:No Plex API found to monitor RAM usage.
DEBUG:Updating Memory voice channel with new Memory percent: N/A
DEBUG:Updated 🐏 Memory: N/A successfully`

**Comment by corruptmods** [comment]
From the change log of tautulli, seems like you can no longer grab the plex token from the API. This may have something to do with it.

**Comment by nwithan8** [comment]
Is this issue still happening?

**Comment by corruptmods** [comment]
Yes. Currently still says N/A for cpu and memory. If I restart the docker it’ll fix itself for a short while. But then right back to N/A.

**Comment by nwithan8** [comment]
Do you see the following line in your logs anywhere?

```Could not prepare Plex API```

**Comment by corruptmods** [comment]
No I do not. Only thing I see in logs when the issues does come up is "No Plex API found to monitor CPU usage" same goes for RAM.

**Comment by identd113** [comment]
As of right now, this is working for me. I'll open a new issue if it goes back to not updating or displaying a ?
