### ISSUE TITLE
[HELP] - Multi Server Support

### ISSUE THREAD

**Issue by TsinJu** [nwithan8/tauticord#230]
### This issue has not already been resolved

- [X] I have verified that no one has asked for help with this issue before.

### You have read the documentation

- [X] I have read the documentation and my issue is not addressed there.

### Installation Type

Standalone Docker

### Configuration Type

Unknown

### Type of Issue

Other

### Issue Details

2nd Server integration

### Steps to Reproduce

Is it possible to display the Activity Stats plus Display settings (Plex Stats, Bandwith etc.) from a 2nd server?

### Logs

no logs

**Comment by nwithan8** [comment]
Tauticord only supports one Tautulli server. To show stats for multiple servers, you will need to run multiple instances of Tauticord (multiple Discord bots).
