### ISSUE TITLE
Feature Request: Split bandwidth into local and remote bandwidth

### ISSUE THREAD

**Issue by RobLaw0304** [nwithan8/tauticord#24]
Offer the option to split bandwidth into local and remote bandwidth and allow hiding of either option.  

Use Case:
I and countless others suffer from having cable internet.  Our download is ample, but upload is severely limited.  Differentiating between LAN and WAN traffic will allow sysadmins to better tune their system to work within the confines of their bandwidth.

**Comment by nwithan8** [comment]
The overview message already displays total and LAN bandwidth as separate elements. Are you referring to the voice channels?
