### ISSUE TITLE
Voice channel library stats update. 

### ISSUE THREAD

**Issue by daskaputtja** [nwithan8/tauticord#29]
In the config.yaml it states that the discord voice channels are meant to update every hour with new stats. 

However after rescanning my library, a few times, it's sticking on the same numbers. I have stopped/started the bot. Deleted the channels to remake them and it's still displaying the same numbers.

**Comment by Metuant** [comment]
I have also been seeing this behavior

**Comment by daskaputtja** [comment]
> I have also been seeing this behavior

So I actually found out what was going on with me... when it was connecting with Tautalli, it was reading deleted channels. I had to go into tautalli and delete them manually. After that I seems to be working like a charm.

**Comment by nwithan8** [comment]
> > I have also been seeing this behavior
> 
> So I actually found out what was going on with me... when it was connecting with Tautalli, it was reading deleted channels. I had to go into tautalli and delete them manually. After that I seems to be working like a charm.

Wait, what did you delete manually? Discord channels, or Tautulli libraries?

**Comment by daskaputtja** [comment]
In Tautalli itself. 

It was displaying multiple libraries of the same name but some with the yellow triangle. So I manually delete the error creating libraries and restarted Tauticord and voila!

**Comment by nwithan8** [comment]
> In Tautalli itself.
> 
> It was displaying multiple libraries of the same name but some with the yellow triangle. So I manually delete the error creating libraries and restarted Tauticord and voila!

Good to know you were able to figure it out.

@Metuant are you still facing this issue?

**Comment by Metuant** [comment]
Yes seems to have resolved this issue for me as well.
