### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#30]
WARNING:We are being rate limited. Retrying in 0.09 seconds. Handled under the bucket "0987123049813:None:/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/@me"

Getting this, then after a while Tauticord stops working.

**Comment by neoTUGA** [comment]
Also getting this

**Comment by slimshizn** [comment]
@neoTUGA any thoughts?

**Comment by Metuant** [comment]
Also getting this

**Comment by slimshizn** [comment]
Recent update seemed to fix it, thank you for your work.

**Comment by nwithan8** [comment]
I didn't change anything, but cool.

**Comment by slimshizn** [comment]
I had the modules/requirement.txt prior to your recent file changes, so something changed within August.

**Comment by dsmitty166** [comment]
I’m seeing this issue in the docker version

**Comment by nwithan8** [comment]
Recent updates to the Docker version of Tauticord *may* fix this.
