### ISSUE TITLE
modules/discord_connector.py change just showing placeholder.

### ISSUE THREAD

**Issue by slimshizn** [nwithan8/tauticord#40]
![Discord_eiEFWNNXgn](https://user-images.githubusercontent.com/23506499/190651421-31a44e2f-3038-4013-8b6b-95bde69a734d.png)
![mRemoteNG_OV52DLCoF8](https://user-images.githubusercontent.com/23506499/190651516-5fe447c2-03b0-4bc8-9148-e849a10eeb78.png)

**Comment by nwithan8** [comment]
Yeah, the past few releases have been to fix this issue.

It seems like the bot is not able to construct a new message. When it has nothing to update the message with, it uses "placeholder" instead.

Can you confirm some things for me:
1) Has the bot ever worked for you? Did this start recently with a specific version or it always did this?
2) is it sending "placeholder" multiple times (are there multiple "placeholder" messages, or is it just editing the same existing one each time?
3) If you turn the bot off and back on, does it make a new/second "placeholder" message, or does it edit the old one?

**Comment by slimshizn** [comment]
The bot has worked for me yes. Placeholder with no embeds started with the most recent update.
It's just editing the same existing one each time.
Restarting it edits the existing message.

**Comment by LubricantJam** [comment]
I'm having this issue from a brand new installation also, it just says "Placeholder". Successfully updates the same one each time, even through container restarts.

**Comment by LubricantJam** [comment]
Confirmed as fixed, thanks!

**Comment by slimshizn** [comment]
Confirmed
