### ISSUE TITLE
System Stats(?)

### ISSUE THREAD

**Issue by JamsRepos** [nwithan8/tauticord#44]
Is it possible to get full system stats included too? Like the full servers bandwidth in/out & CPU, RAM usage?

As whilst Tautulli does do some reporting, users can't really see if the server itself is performing well.

**Comment by nwithan8** [comment]
All the data Tauticord presents currently comes from Tautulli's API.

We could explore providing that information, but it would require the bot to run on the same system as Tautulli (or to interact with some API/plugin that provides system information)

**Comment by JamsRepos** [comment]
Not sure if you were awaiting my response or not to this but i'd say this would be fine, most people would have the bot running on the same system as Tautulli. I myself have two seperate servers and I only have Plex on the main server. Would of course be a toggle basis too no doubt.

**Comment by nwithan8** [comment]
<img width="208" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/dc4f2c54-b94d-4f44-9a8e-e5f79ea89fba">
