### ISSUE TITLE
Ability to Rename Channels

### ISSUE THREAD

**Issue by LubricantJam** [nwithan8/tauticord#45]
Can we get the ability to rename the channels? I'd love to put an emoji in the name of the channel rather than the full name, as on certain devices channels can't be read properly. 

So "TV Shows:" I could change to "📺 Total:"

**Comment by slimshizn** [comment]
> Can we get the ability to rename the channels? I'd love to put an emoji in the name of the channel rather than the full name, as on certain devices channels can't be read properly.
> 
> So "TV Shows:" I could change to "📺 Total:"

Should be able to use :tv: Total:

**Comment by LubricantJam** [comment]
> > Can we get the ability to rename the channels? I'd love to put an emoji in the name of the channel rather than the full name, as on certain devices channels can't be read properly.
> > So "TV Shows:" I could change to "📺 Total:"
> 
> Should be able to use : tv : Total: (without the spaces in between)

My point is you cannot rename the channels, only the categories. I'd like to rename the channels.

**Comment by nwithan8** [comment]
The channel names are dictated by the library name on Plex, meaning they have to match.
To support alternative Discord channel names for each Plex library would require a complex remapping that would bloat the configuration.

I'm going to veto this idea, sorry.
