### ISSUE TITLE
Server online status?

### ISSUE THREAD

**Issue by hardheadjed** [nwithan8/tauticord#47]
Is there a way to display the server online/offline status as a channel name?

**Comment by nwithan8** [comment]
Are you referring to whether Tautulli is online, or whether the Plex Server that Tautulli is monitoring is online?

**Comment by hardheadjed** [comment]
The Plex server. Sorry for not being more clear earlier.

**Comment by nwithan8** [comment]
Added in v1.4.0

**Comment by hardheadjed** [comment]
Thanks!
