### ISSUE TITLE
Failed to start the application 

### ISSUE THREAD

**Issue by ShadesOfMoon** [nwithan8/tauticord#50]
Hello, I followed attentively all the prerequisites necessary to the execution of the script, however I still have a problem during the execution of this one I put you the screenshot of the problem in question, hoping that you can enlighten me on the subject.

![Capture d’écran 2022-12-20 150816](https://user-images.githubusercontent.com/116625107/208686071-28008015-abae-4c75-95f4-467adb0f640d.png)

**Comment by jimi4121** [comment]
Same error here

**Comment by nwithan8** [comment]
It looks like it's not finding your server ID in your configuration file. Did you fill out the file? Are you using this as Docker or running it as a Python script directly?

**Comment by ShadesOfMoon** [comment]
Yes, my id is set. (I use for the moment like a script) 

ID is set on the config file

**Comment by nwithan8** [comment]
Seems a rogue comment in the config file might have been invalidating the configuration during parsing. Minor clarifications made to rectify this. Closing as fixed.
