### ISSUE TITLE
Tauticord auto killing every stream

### ISSUE THREAD

**Issue by Lonewolf147** [nwithan8/tauticord#52]
Fresh install, first time using, everything works, but as soon as a stream is detected, it posts, but then immediately reacts and kills the stream. The logs look like this when it happens:

DEBUG:Count: 1
2023-01-01 16:36:51,765 - [INFO]: Updating Streams voice channel with new stream count: 1
INFO:Updating Streams voice channel with new stream count: 1
2023-01-01 16:36:51,923 - [INFO]: Updating Transcodes voice channel with new stream count: 1
INFO:Updating Transcodes voice channel with new stream count: 1
2023-01-01 16:36:52,095 - [INFO]: Updating Bandwidth voice channel with new bandwidth: 2.6 Mbps
INFO:Updating Bandwidth voice channel with new bandwidth: 2.6 Mbps
2023-01-01 16:36:52,351 - [INFO]: Updating Remote Bandwidth voice channel with new bandwidth: 0.0 bps
INFO:Updating Remote Bandwidth voice channel with new bandwidth: 0.0 bps
DEBUG:Using old message...
DEBUG:Editing old message...
DEBUG:Stopping stream 1️⃣...
2023-01-01 16:36:53,807 - [INFO]: User attempting to stop session 1️⃣, id c3a96bcac397ffb7-com-plexapp-android
INFO:User attempting to stop session 1️⃣, id c3a96bcac397ffb7-com-plexapp-android
2023-01-01 16:36:54,275 - [INFO]: Stream 1️⃣ was stopped.
INFO:Stream 1️⃣ was stopped.
DEBUG:JSON returned by GET request: {'stream_count': '0', 'sessions': [], 'stream_count_direct_play': 0, 'stream_count_direct_stream': 0, 'stream_count_transcode': 0, 'total_bandwidth': 0, 'lan_bandwidth': 0, 'wan_bandwidth': 0}
DEBUG:Count: 0

**Comment by nwithan8** [comment]
Thanks for the ticket.

The bot had a similar issue before, but I thought I had fixed it.

Will look into it.

**Comment by Lonewolf147** [comment]
Thank you.

**Comment by nwithan8** [comment]
Looking through the code, the bot is supposed to only consider message reactions that are posted by admin users.

In the "Admin IDs" section of your config.yaml file, do you perhaps have the bot ID? If so, remove it.

**Comment by neoTUGA** [comment]
So, i didnt have "admin IDs" i still had ownerid, so i deleted the whole docker container, re did everything from scratch. and now nothing works.. haha 
Endless loop of:

2023-01-09 10:22:47,943 - [INFO]: Starting Tauticord...
2023-01-09T10:22:48: PM2 log: App [monitor:2] exited with code [1] via signal [SIGINT]
2023-01-09T10:22:48: PM2 log: App [monitor:2] starting in -fork mode-
2023-01-09T10:22:48: PM2 log: App [monitor:2] online

**Comment by neoTUGA** [comment]
As I suspected, my error on the config. 
To stop the auto killing stream, update the config.yaml to the new one, enter all of your data, and it works as it should :)
Old config had "OwnerID" instead of "AdminIDs".
Sorry for the hassle.

**Comment by Lonewolf147** [comment]
Where do I find the config.yaml file in unRaid?

**Comment by nwithan8** [comment]
> Where do I find the config.yaml file in unRaid?

If you enter the Docker container with `docker exec -it <container_name> bash`, you should see the `config.yaml` file right there in the file system. (Good idea though, I'd like to add mapping so you can access the file from your parent OS)

You can also set variables via Docker environmental variables rather than bothering with a `config.yaml` file.

**Comment by Lonewolf147** [comment]
I'm not very familiar with linux in any form (been playing with unraid for a bit and I'm learning). So, I did the bash command and then ran ls to see the files. Here's what it shows:

root@Valaskjalf:/app# ls
Dockerfile  LICENSE  README.md  Tauticord.log  Tauticord.py  config.yaml.example  docker-compose.yml  modules  requirements.txt

I see A config file, but it is set as an example file. I don't see any other active config file though. Even so, how do I edit this file form an unraid command line? OR, where exactly is this directory located, is it possible to navigate to it in doublecommander? And finally, if I were to just add it as an environmental variable, can you tell me exactly what I would need to put in? (I do know how to edit the docker template and add items, I just don't know WHAT I would need to add specifically in this case).

**Comment by Lonewolf147** [comment]
Just saw the new update, made a post on your discord channel about it. 
Thanks.

**Comment by nwithan8** [comment]
> I'm not very familiar with linux in any form (been playing with unraid for a bit and I'm learning). So, I did the bash command and then ran ls to see the files. Here's what it shows:
> 
> root@Valaskjalf:/app# ls
> Dockerfile  LICENSE  README.md  Tauticord.log  Tauticord.py  config.yaml.example  docker-compose.yml  modules  requirements.txt
> 
> I see A config file, but it is set as an example file. I don't see any other active config file though. Even so, how do I edit this file form an unraid command line? OR, where exactly is this directory located, is it possible to navigate to it in doublecommander? And finally, if I were to just add it as an environmental variable, can you tell me exactly what I would need to put in? (I do know how to edit the docker template and add items, I just don't know WHAT I would need to add specifically in this case).

If you're on Unraid, I'd recommend using the Community Applications template for Tauticord (a nice GUI to help you set environmental variables, just "install" Tauticord from Community Applications). I am in the process of updating the template since it's outdated; I'll let you know when it's good to go.

**Comment by Lonewolf147** [comment]
> > I'm not very familiar with linux in any form (been playing with unraid for a bit and I'm learning). So, I did the bash command and then ran ls to see the files. Here's what it shows:
> > root@Valaskjalf:/app# ls
> > Dockerfile  LICENSE  README.md  Tauticord.log  Tauticord.py  config.yaml.example  docker-compose.yml  modules  requirements.txt
> > I see A config file, but it is set as an example file. I don't see any other active config file though. Even so, how do I edit this file form an unraid command line? OR, where exactly is this directory located, is it possible to navigate to it in doublecommander? And finally, if I were to just add it as an environmental variable, can you tell me exactly what I would need to put in? (I do know how to edit the docker template and add items, I just don't know WHAT I would need to add specifically in this case).
> 
> If you're on Unraid, I'd recommend using the Community Applications template for Tauticord (a nice GUI to help you set environmental variables, just "install" Tauticord from Community Applications). I am in the process of updating the template since it's outdated; I'll let you know when it's good to go.

That's where I was getting it from in the first place. I just assumed that when it was updated on GitHub it would updated CA too. I'll hang tight until you say it's good.
 Thanks for the work!  This is a great app.

**Comment by nwithan8** [comment]
Awaiting https://github.com/selfhosters/unRAID-CA-templates/pull/370

**Comment by nwithan8** [comment]
Update: The template for the selfhosters repo is taking a while in review. I've decided to start my own Unraid template repository, in talks with the Community Apps developer to get my repository added to the list. Will allow me to have full autonomy over the template and get it updated on my own terms.

**Comment by Lonewolf147** [comment]
Sounds good. I changed the owner_id to admins_id and that fixed the issue for now.

**Comment by nwithan8** [comment]
The Tauticord template for selfhosters has been removed and added via my personal repository. If you search "Tauticord" in Community Apps in Unraid, you should only see one entry from "grtgbln's repository", that's my template with the updated data. Please use that template going forward.
