### ISSUE TITLE
display stats in text channel

### ISSUE THREAD

**Issue by bison529** [nwithan8/tauticord#67]
Hi,

can stats of Tautulli displayed within a text channel?
because I have many plex servers and can't display stats of Tautulli in voice channel.

thanks

**Comment by nwithan8** [comment]
What is preventing you from using the voice channels?

**Comment by nwithan8** [comment]
This has been included in https://github.com/nwithan8/tauticord/pull/70/commits/74b179156517bb09bae428092e46e787c5115e6c and is being rolled into the next version.
