### ISSUE TITLE
Doesn't like "/" in library name

### ISSUE THREAD

**Issue by edrock200** [nwithan8/tauticord#68]
Thanks for making this awesome bot!

I think I found a small bug. I have a library named "PPV / Events"

It won't pull stats for this library. All others work. I'm guessing it's the "/"

Log entries

`2023-02-26 00:48:46,806 - [INFO]: Collecting stats about library "PPV / Events"
INFO:Collecting stats about library "PPV / Events"
2023-02-26 00:48:46,826 - [ERROR]: Could not get ID for library PPV / Events
ERROR:Could not get ID for library PPV / Events
2023-02-26 00:48:46,826 - [INFO]: Updating PPV / Events voice channel with new library
size: 0
INFO:Updating PPV / Events voice channel with new library size: 0`

**Comment by edrock200** [comment]
Confirmed. Renamed library to just "Events" and it works now

**Comment by nwithan8** [comment]
Will look into it, thanks for reporting

**Comment by nwithan8** [comment]
Hmm, I made my own library called "PPV / Events", but wasn't able to re-create the bug. Perhaps there was an extra space floating around somewhere?
