### ISSUE TITLE
Channels now Unreadable

### ISSUE THREAD

**Issue by LubricantJam** [nwithan8/tauticord#71]
As you can see in  your example image too, the statistics are now cut off and no longer display the number properly just simply an ellipsis.

Could I suggest the ability to use emojis instead of the name for a more low profile look and to allow more digits? You can see what I've managed to achieve with Notifiarr below the Tauticord stats. 

![Image](https://i.imgur.com/CUkEHgq.png)

**Comment by LubricantJam** [comment]
This could look like the following:
```
🎬 Total: 15,641
📺 Series: 4,744
📺 Episodes: 192,437
```

**Comment by nwithan8** [comment]
I was thinking of upgrading to emojis anyway.

Question though, since it's "shows per library, episodes per library", I would need an emoji that can represent shows, an emoji that can represent episodes, etc.

Any suggestions?

**Comment by LubricantJam** [comment]
Wouldn't it be easier to have a emoji per category rather than each media type? So you'd have one for anime, etc. 

Or I guess that wouldn't work for people that separate their Movies, Movies 4K, Movies Old, etc. 

I was thinking perhaps `🧩` for a episode, as it would represent a puzzle as it requires multiple pieces to make it whole?
Or maybe even `📼` although more aimed around movies, it's still a type of content we used to have back in the ol' days.
Or maybe using the VHS one for the Series instead, and then using `🎞️` as a subsidiary of a VHS.

Just a couple ideas from me :)

**Comment by LubricantJam** [comment]
@nwithan8 could the emojis be at the front of the string? It looks a tad off with different library name lengths pushing the emojis all over the place.

**Comment by nwithan8** [comment]
> @nwithan8 could the emojis be at the front of the string? It looks a tad off with different library name lengths pushing the emojis all over the place.

Sure, why not? I read it as "Library Name Movies", "Library Name Shows", but I see your point, will change.

**Comment by nwithan8** [comment]
Much better, good suggestion.
<img width="236" alt="image" src="https://user-images.githubusercontent.com/17054780/225509896-29f98056-af13-4555-a38f-b0bf3500b6b5.png">

If the library can't be pulled (doesn't exist), it will use a question mark emoji to signify something is wrong.

**Comment by costispavlou** [comment]
> ![Image](https://camo.githubusercontent.com/8c488d8fbdb748150963e709312338049b1fc09fb05d5c368380eaa12044bfe2/68747470733a2f2f692e696d6775722e636f6d2f43556b454867712e706e67)

would you please explain how you added the Upgraded / Added channels ?

**Comment by LubricantJam** [comment]
> > ![Image](https://camo.githubusercontent.com/8c488d8fbdb748150963e709312338049b1fc09fb05d5c368380eaa12044bfe2/68747470733a2f2f692e696d6775722e636f6d2f43556b454867712e706e67)
> 
> 
> 
> would you please explain how you added the Upgraded / Added channels ?

Notifiarr.

**Comment by costispavlou** [comment]
> 

Right but how does that link to tauticord ?

**Comment by LubricantJam** [comment]
> > 
> 
> 
> 
> Right but how does that link to tauticord ?

I never said it did.
