### ISSUE TITLE
Provide Progress Bar or Progress Details?

### ISSUE THREAD

**Issue by vember31** [nwithan8/Tauticord#8]
Would love if the Tauticord notification could show the progress of what's being watched.  This could be in the form of something like '5:00/45:00 (11%)   ETA: 18:32' or something, and/or a progress bar similar to what is shown in Tautulli at the bottom of a 'now playing' notification.

E.g. a means of displaying this data within the Discord notification that Tauticord creates:

![image](https://user-images.githubusercontent.com/17370796/104051195-5f993400-51ad-11eb-9216-5843b42162de.png)

**Comment by nwithan8** [comment]
Added in 0886d8878968c3b2efb544ccb7b9818184c89c1c, great idea
