### ISSUE TITLE
Enable multiple Plex servers to run concurrently

### ISSUE THREAD

**Issue by mtrogman** [nwithan8/tauticord#81]
With Voice Channel names hard coded you are only able to run script per discord server.  If you have multiple plex servers you cannot run script as they voice channels will keep overwriting themselves.

**Comment by nwithan8** [comment]
You can make two voice channels with the same name in different categories in Discord.

So if you make one Tauticord instance category name "Plex Server 1" and the second "Plex Server 2", they should be able to co-exist.

**Comment by nwithan8** [comment]
I know the idea has been floated of adding additional configuration options to change the prefix for each server, allowing multiple servers to be in the same voice channel category.

```
Stats:
- Server1 Streams
- Server2 Streams
```

Instead, users should use the existing `CategoryName` settings:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/17054780/236657801-71e36339-dd5c-40d1-bc89-c67644e66c32.png">


This will instead produce a voice channel category for each server.

```
Server1 Stats:
- Streams

Server2 Stats:
- Streams
```
