### ISSUE TITLE
Anon Enhancement

### ISSUE THREAD

**Issue by JamsRepos** [nwithan8/tauticord#87]
Instead of showing "Anonymous" and essentially nullifying names etc, would it be better UX to just not include it at all? As it's not really needed information at all at that point, device could just be Plex Web etc too, without (Anonymous) too.

That way, the channel can be displayed to most users in the Discord, whilst keeping anoniminity and not having people ask "Why does it say Anonymous?".

**Comment by JamsRepos** [comment]
@nwithan8 Sorry, not at home so the fucker posted before typing the contents 🤣

**Comment by benwaco** [comment]
Personally prefer it saying anonymous, he could add a subsection to the configuration file with these parameters (hide name, hide hostname, hide terminate, etc...)

**Comment by JamsRepos** [comment]
Yeah, no doubt it'll be on a toggle state. More preference options, the better.

**Comment by nwithan8** [comment]
Define your own replacement word to replace username/player/product, hide bandwidth/transcoding status/progress/ETA all independently
<img width="362" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/b719346d-ca5f-4551-a5b3-6fecbd3e2b58">
<img width="295" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/84d60d1d-7d54-45d0-a784-4697e18987d0">


Or go all out and use a blank string as your replacement word to basically hide everything
<img width="379" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/84f60a9a-3f29-4380-94c3-2e3eaab5f9e7">
<img width="290" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/5b78781c-1d7f-4ec9-8b2f-523fa730764a">

**Comment by nwithan8** [comment]
Even better:

Replace usernames/platforms/players:
<img width="349" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/716ec03a-6c72-4143-8165-021322daf905">
<img width="318" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/32f56bd8-afca-4886-b630-76c568d9f89f">


Versus hide:
<img width="341" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/515a6121-0cf5-4534-8849-077825f996e1">
<img width="272" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/598e91c1-c6cb-41db-8e78-74070817f987">

**Comment by JamsRepos** [comment]
I was about to say, would be better if it just hides completely on a blank string but you seem to have covered that there.

**Comment by nwithan8** [comment]
Eh, I don't like that as much. Too much complexity trying to account for replacement versus hidden.

Simplifying it:
<img width="297" alt="image" src="https://github.com/nwithan8/tauticord/assets/17054780/152728c0-ac22-4cc0-8588-99b444fbd425">


You can't replace anything (sorry, no replacing usernames with "Anonymous"), just excluding it if you want to hide it.
