### ISSUE TITLE
Daily Overview

### ISSUE THREAD

**Issue by JamsRepos** [nwithan8/tauticord#89]
It would be nice, if we could have an option to have a daily overview (doesn't have to be daily, could be weekly, monthly, or just disabled etc) where it would print a pretty discord embed in a selected channel of a little breakdown of recent media in X library added within the time period, what was the most watched, what was popular, who watched the most (if anon is not enabled) etc, as this is information that to me, is great to have but it's also quite nice to share that information with friends in the discord without needing to make them individual guest accounts on tautulli (which then can't see usernames anyways as it all says Guest) and you know, we all love a pretty Discord embed.

**Comment by nwithan8** [comment]
A majority of these features have been added as manual slash commands, now available in v4.0.0 of Tauticord.
